export const products = [
  {
    id: 1,
    name: "Air Jordan 40 PF ‘Blue Suede’",
    category: "Basketball Shoes",
    price: 11495,
    image: "/images/blue-suede.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
  {
    id: 2,
    name: "Nike Runner",
    category: "Men's Shoes",
    price: 7495,
    image: "/images/shattered-backboard.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
  {
    id: 3,
    name: "Adidas Classic",
    category: "Men's Shoes",
    price: 6295,
    image: "/images/cmft-era.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
    {
    id: 4,
    name: "Air Jordan 40 PF ‘Blue Suede’",
    category: "Basketball Shoes",
    price: 11495,
    image: "/images/blue-suede.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
  {
    id: 5,
    name: "Nike Runner",
    category: "Men's Shoes",
    price: 7495,
    image: "/images/shattered-backboard.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
  {
    id: 6,
    name: "Adidas Classic",
    category: "Men's Shoes",
    price: 6295,
    image: "/images/cmft-era.png",
    sizes: [6, 7, 8, 9, 10, 11, 12],
  },
];
